package com.roche.connect.common.constant;

public enum NotificationGroupType {
     LOCALE("en_US"),
     NO_ORDER_FOUND_MP24("NO_ORDER_FOUND_MP24"),
     NO_ORDER_FOUND_LP24("NO_ORDER_FOUND_LP24"),
     UNSUPPORTED_HL7_MSG_MP24("UNSUPPORTED_HL7_MSG_MP24"),
     UNSUPPORTED_HL7_MSG_LP24("UNSUPPORTED_HL7_MSG_LP24"),
     INVALID_HL7_VER_MP24("INVALID_HL7_VER_MP24"),
     INVALID_HL7_VER_LP24("INVALID_HL7_VER_LP24"),
     MISSING_INFO_MP24("MISSING_INFO_MP24"),
     MISSING_INFO_LP24("MISSING_INFO_LP24"),
     UNREGISTERED_DEVICE_MP96("UNREGISTERED_DEVICE_MP96"),
     UNREGISTERED_DEVICE_DPCR("UNREGISTERED_DEVICE_dPCR"),
     INVALID_HL7_VER_MP96("INVALID_HL7_VER_MP96"),  
     INVALID_HL7_VER_DPCR("INVALID_HL7_VER_dPCR"),
     INVALID_DEVICE_MODEL_MP96("INVALID_DEVICE_MODEL_MP96"),
     DEVICE_OFFLINE_MP96("DEVICE_OFFLINE_MP96"),
     DEVICE_OFFLINE_DPCR("DEVICE_OFFLINE_dPCR"),
     UNREGISTERED_DEVICE_MP24("UNREGISTERED_DEVICE_MP24"),
     INVALID_DEVICE_MODEL_MP24("INVALID_DEVICE_MODEL_MP24"),
     DEVICE_OFFLINE_MP24("DEVICE_OFFLINE_MP24"),
     UNREGISTERED_DEVICE_LP24("UNREGISTERED_DEVICE_LP24"),
     INVALID_DEVICE_MODEL_LP24("INVALID_DEVICE_MODEL_LP24"),
     INVALID_DEVICE_MODEL_DPCR("INVALID_DEVICE_MODEL_dPCR"),
     DEVICE_OFFLINE_LP24("DEVICE_OFFLINE_LP24"),
     UNSUPPORTED_EQUIP_STATUS_MP24(" UNSUPPORTED_EQUIP_STATUS_MP24"),
     UNSUPPORTED_EQUIP_STATUS_LP24("UNSUPPORTED_EQUIP_STATUS_LP24"),
     INCORRECT_RUN_DETAILS_HTP("INCORRECT_RUN_DETAILS_HTP"),
     INCORRECT_RUN_ID_HTP("INCORRECT_RUN_ID_HTP"),
     INVALID_RUN_STATUS_RECEIVED_FROM_HTP("INVALID_RUN_STATUS_RECEIVED_FROM_HTP"),
     MISSING_CYCLE_NUMBER_HTP("MISSING_CYCLE_NUMBER_HTP"),
     INVALID_COMPLX_ID_HTP("INVALID_COMPLX_ID_HTP"),
     INVALID_DATA_TRANSFER_INFO_HTP("INVALID_DATA_TRANSFER_INFO_HTP"),
     UNREGISTERED_DEVICE_HTP("UNREGISTERED_DEVICE_HTP"),
     MUL_MSG_DIFF_STATUS_MP24("MUL_MSG_DIFF_STATUS_MP24"),
     MUL_MSG_DIFF_STATUS_LP24("MUL_MSG_DIFF_STATUS_LP24"),
     FILE_SIZE_EXCEEDS_LIMIT_HTP("FILE_SIZE_EXCEEDS_LIMIT_HTP"),
     DEVICE_OFFLINE_HTP("DEVICE_OFFLINE_HTP"),
     INVALID_DEVICE_ID_HTP("INVALID_DEVICE_ID_HTP"),
     OUT_OF_SEQ_CYCLE_NUMBER_HTP("OUT_OF_SEQ_CYCLE_NUMBER_HTP"),
     OUT_OF_SEQ_MSG_HTP("OUT_OF_SEQ_MSG_HTP"),
     RESULT_REJECTED_DPCR("RESULT_REJECTED_dPCR"),
 	INVALID_PLATE_ID_DPCR_DESC("INVALID_PLATE_ID_DPCR"),
 	DUPLICATE_PLATE_ID_DPCR_DESC("DUPLICATE_PLATE_ID_DPCR"),
 	INCOMPLETE_PLATE_DPCR_DESC("INCOMPLETE_PLATE_DPCR"),
 	NO_ORDER_FOUND_DPCR_DESC("NO_ORDER_FOUND_dPCR"),
 	MISSING_INFO_DPCR_DESC("MISSING_INFO_DPCR"),
 	MUL_MSG_DIFF_STATUS_DPCR_DESC("MUL_MSG_DIFF_STATUS_dPCR"),
 	MISSING_INFO_MP96_DESC("MISSING_INFO_MP96"),
 	PLATE_RESULTS_MAPPING_MISSING_MP96DESC("PLATE_RESULTS_MAPPING_MISSING_MP96"),
    INSTRU_TRIGGER_HTP_2("INSTRU_TRIGGER_HTP_2"),
    INSTRU_TRIGGER_HTP_3("INSTRU_TRIGGER_HTP_3"),
    INSTRU_TRIGGER_HTP_1("INSTRU_TRIGGER_HTP_1"),
    INSTRU_TRIGGER_HTP("INSTRU_TRIGGER_HTP"),
	PRBLM_RPRT_GEN("PRBLM_RPRT_GEN"),
	PRBLM_RPRT_NOT_GEN("PRBLM_RPRT_NOT_GEN"), BACKUP_TRIGGER_GEN_2("BACKUP_TRIGGER_GEN_2"), BACKUP_TRIGGER_GEN_3("BACKUP_TRIGGER_GEN_3"), BACKUP_TRIGGER_GEN_1("BACKUP_TRIGGER_GEN_1"),BACKUP_TRIGGER_GEN_4("BACKUP_TRIGGER_GEN_4");
    
     private NotificationGroupType(String value) {
         this.value = value;
     }
     
     String value;
     
     public String getGroupType() {
 		return this.value;
 	}
}