pas:
    #Permission for the User to access this microservice
    #microservice_permission: Access_htp-adapter
    security.method.disable : false
    
    security_endpoint: ${pas.security_remote_url}
    metadata_endpoint: ${pas.metadata_remote_url}
    device_endpoint: ${pas.device_remote_url}
    email_endpoint: ${pas.email_remote_url}
    simple_api_endpoint : ${pas.application_remote_url}
    locale_endpoint: ${pas.locale_service_remote_url}
    
    #application_location - values [default,distributed]
    #If value is default, it is assumed that all microservices are running in same location (www.perf-rocheconnect.com is used through-out app)
    application_location : default

    application_host_name :  www.perf-rocheconnect.com
    application_url : https://${pas.application_host_name}:98
    
    application_ui_host_name :  www.perf-rocheconnect.com
    application_ui_url : https://${pas.application_ui_host_name}:93/admin-ui
    
    security_host_name :  www.perf-rocheconnect.com
    security_url : https://${pas.security_host_name}:90/security-web
    authenticate_url: ${pas.security_url}/json/security/login
    username: admin
    password: pas123
    org: hcl.com
    login_entity: j_username=${pas.username}&j_password=${pas.password}&org=${pas.org}
    
    metadata_host_name :  www.perf-rocheconnect.com
    metadata_url : https://${pas.metadata_host_name}:91/metadata-web
    
    metadata_remote_host_name :  www.perf-rocheconnect.com
    metadata_remote_url : https://${pas.metadata_remote_host_name}:91/metadata-web

    device_host_name :  www.perf-rocheconnect.com
    device_url : https://${pas.device_host_name}:85/device-management
    
    device_remote_host_name :  www.perf-rocheconnect.com
    device_remote_url : https://${pas.device_remote_host_name}:85/device-management

    security_remote_host_name :  www.perf-rocheconnect.com
    security_remote_url : https://${pas.security_remote_host_name}:90/security-web

    application_remote_host_name :  www.perf-rocheconnect.com
    application_remote_url : https://${pas.application_remote_host_name}:98/htp-adapter

    admin_api_host_name :  www.perf-rocheconnect.com
    admin_api_url : https://${pas.admin_api_host_name}:92/admin-api
    
    login_url : ${pas.application_ui_url}/login.jsp
    
    defaultHomePage : ${pas.application_ui_url}/listuser.mvc
    
    locale_service_remote_url : ${pas.admin_api_url}
    
    email_remote_host_name : www.perf-rocheconnect.com
    email_remote_url : https://${pas.email_remote_host_name}:94/email-web
    
    access_control_allow_origin : https://localhost:4200
    
    default_company_for_user_provisioning : hcl.com

    #access_denied_url : /accessdenied.jsp

    #service registry check - default value server change as client if service registry is enabled
    service.discovery: server
    
    #Auditable History enable or disable -defauls value is true
    auditable_history: true
    auditable_history_days: 30
    
    #To enable and disable rabbitMQ- default value false
    rabbitmq.enabled: false

    support_for_http_and_https: false
    http_port: 80
    
    transaction.enabled: true
            
    companyName : root Company
    description : root company
    domainName : hcl.com
    companyType : PASCOMPANY

    encryption_salt : user@domain
    encrypt_password : domain@user
    no_of_iteration : 1

    expiryValue : 5

    keystore_location : keystore/pas.jceks
    keystore_pass : pas123
    keystore_type : jceks
    token_private_key_pass : pas123
    token_private_key_alias : pasprivatekey
    token_public_key_alias : paspublickey
    symmetric_key_alias : passymmetrickey
    symmetric_key_pass : pas123


    fileName_Prefix : brownstone_app_init
    XL_Location : excels
    query_Location : generated-app/query 
    XL_Prefix : app

    poll_enabled : true
    poll_attempts : 10
    poll_attempts_delay_in_seconds : 30
    poll_url : ${pas.metadata_remote_url}/poll, ${pas.security_remote_url}/poll

    logged_module_name : htpforte-adpater
    application_module_name : htpforte-adpater

    rabbitmq:
        exchangename : pasExchange
        hierarchyqueuename : simpleAPIHierarchyQueue
        userqueuename : simpleAPIUserQueue
        userdeletequeuename : simpleAPIUserDeleteQueue
        userupdatedqueuename : simpleAPIUserUpdatedQueue
        datasource_changes_queue : applicationDatasourceChangeQueue        

    hierarchy_sync_exclude : 

    whitelist_urls : 

    datasource.class : com.mchange.v2.c3p0.ComboPooledDataSource
    
    version: 0.0.1-SNAPSHOT
    title: ${pas.logged_module_name} - REST documentation
    contact_email: PBASolutionsteam@hcl.in
    api_description: These are the contracts for the rest services exposed in this ${pas.logged_module_name}.    
    
    customizableservice.metadata.capture: false
    eventpublishing.queue.default_name: pasQueue
    
spring.main.show-banner: false
endpoints.enabled: false       
spring.profiles.active: full,permission
spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true

management:
    contextPath: /poll

#Make it true if service registry is required, default value is false 
spring.cloud.consul.enabled: false

logging.path: '/var/log/connect/log'
logging.file: HTP-Forte-adapter.log
logging.config: 'classpath:log4j2.xml'

spring.rabbitmq.host : www.perf-rocheconnect.com
spring.rabbitmq.port : 5672
spring.rabbitmq.username : userone
spring.rabbitmq.password : userone

# To disable the default configuration for the freemarker
# configuration to search for the templates
# TO BE IGNORED ALWAYS: Since String template loader is used
spring.freemarker.checkTemplateLocation: false

server:
    port: 98
    session-timeout: 600
    context-path: /
    ssl.enabled : true
    ssl.key-store: /home/rconnect/roche/crts/KeyStore.jks
    ssl.key-store-password: changeit
    ssl.keyStoreProvider : SUN
    ssl.keyStoreType : JKS
    ssl.keyAlias: www.perf-rocheconnect.com
       

spring.datasource.jdbcUrl : jdbc:postgresql://www.perf-rocheconnect.com:5432/htp_forte_adapter
spring.datasource.user : postgres
spring.datasource.password : postgres123
spring.datasource.minPoolSize : 5
spring.datasource.maxPoolSize : 20
spring.datasource.acquireIncrement : 1
spring.datasource.idleConnectionTestPeriod : 3000
spring.datasource.testConnectionOnCheckout : true
spring.datasource.driverClass : org.postgresql.Driver

spring.jpa.database-platform : org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql : false
spring.jpa.hibernate.ddl-auto : update
spring.jpa.generate-ddl : true
spring.jpa.properties.hibernate.cache.use_second_level_cache : true
spring.jpa.properties.hibernate.cache.use_query_cache : true
spring.jpa.properties.hibernate.cache.use_structured_entries : false
spring.jpa.properties.hibernate.cache.use_minimal_puts : false
spring.jpa.properties.hibernate.cache.generate_statistics : false
spring.jpa.properties.hibernate.cache.provider_configuration : /ehcache.xml
spring.jpa.properties.hibernate.cache.region.factory_class : org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
spring.jpa.properties.javax.persistence.sharedCache.mode : ENABLE_SELECTIVE

#default value is false, change it to true if https is enabled
https_enabled: true

device:
   HTPDeviceType: '364d7266-8544-4714-b275-5943980ad2fa'
   ForteDeviceType: '364d7266-8544-4714-b275-5943980ad2fa'
   pingDelay: 30000
   frequency: 1000
   device_validate: true

adapter:
    htp_mount: '/home/rconnect/roche/ips'
    htp_regEx : 'runs/'
    forte_mount: '/home/rconnect/roche/forte/'
    imm_host_name: www.perf-rocheconnect.com
    imm_host_name_url: https://${adapter.imm_host_name}:9090
    imm_run: ${adapter.imm_host_name_url}/imm/json/rest/api/v1/runs
    imm_run_update: ${adapter.imm_host_name_url}/imm/json/rest/api/v1/runs
    imm_run_get: ${adapter.imm_host_name_url}/imm/json/rest/api/v1/runs
    imm_complex_id_details: ${adapter.imm_host_name_url}/imm/json/rest/api/v1/orders
    imm_getPatientDetails: ${adapter.imm_host_name_url}/imm/json/rest/api/v1/messages
    adm_host_url: https://www.perf-rocheconnect.com:7070/adm
    adm_notification_url : ${adapter.adm_host_url}/json/rest/api/v1/notification
    # convert the given size to bytes and place below without spaces
    cycleFileSize: fastq=576716800,PrimaryAnalysisVersionInfo<1024,metrics=10240,ExpState=153600,ExpAnno=15360

async:
    thread-name-prefix: AsyncCycleTaskExecutor
    core-pool-size: 4
    max-pool-size: 4
