#######################################################
# configure the following parameters only when this is application web app.
# until a centralized config is created.
#configure host name and url for this application
#URLs DEFINED FOR BROWSER COMMUNICATION
#urls to be configured when setting for https
#######################################################
pas:
    #Permission for the User to access this microservice
    microservice_permission: Access_Admin_API
    security.method.disable : false
    
    #Remote endpoints
    security_endpoint: ${pas.security_remote_url}
    metadata_endpoint: ${pas.metadata_remote_url}
    email_endpoint: ${pas.email_remote_url}
    locale_endpoint: ${pas.locale_service_remote_url}
    
    #application_location - values [default,distributed]
    #If value is default, it is assumed that all microservices are running in same location (www.qa-rocheconnect.com is used through-out app)
    application_location : default
    
    application_host_name :  www.qa-rocheconnect.com
    application_url : https://${pas.application_host_name}:92/admin-api
    
    #urls to be configured when Reset password
    application_ui_host_name :  www.qa-rocheconnect.com
    application_ui_url : https://${pas.application_ui_host_name}:93/admin-ui
    
    
    #configure host name and url for security web app.
    security_host_name :  www.qa-rocheconnect.com
    security_url : https://${pas.security_host_name}:90/security-web
    
    #configure host name and url for metadata web app.
    metadata_host_name :  www.qa-rocheconnect.com
    metadata_url : https://${pas.metadata_host_name}:91/metadata-web
    
    #URLs DEFINED FOR INTERNAL WAR COMMUNICATION
    #urls to be configured when setting for https- incase internal war 
    #communication also to be done through https
    metadata_remote_host_name :  www.qa-rocheconnect.com
    metadata_remote_url : https://${pas.metadata_remote_host_name}:91/metadata-web

    security_remote_host_name :  www.qa-rocheconnect.com
    security_remote_url : https://${pas.security_remote_host_name}:90/security-web

    application_remote_host_name :  www.qa-rocheconnect.com
    application_remote_url : https://${pas.application_remote_host_name}:92/admin-api

    partitioned_application_host_name : www.qa-rocheconnect.com
    partitioned_application_url : https://${pas.partitioned_application_host_name}//b2b-application-partition-template
        
    # Change this if you are providing a custom login page.
    # if page in application is provided, exclude that resource from protection as in the following example
    #  <security:http pattern="/custom-login.jsp" security="none" request-matcher="ant"/>
    login_url : ${pas.application_ui_url}/login.jsp
    
    #Enable this property for Emergency user login
    #enable_token_login : true
    #emergency_user_permission: Emergency_User
    #emergency_user_token_expiry: 30
    #session_validity_hours: 1
    #emeregncency_user.token_length: 16
    #emeregncency_user.token_spacing: 4
    #emeregncency_user.token_spacing_char: "-"
    
    defaultHomePage : ${pas.application_ui_url}/listuser.mvc
    
    #configure host name and url for Email API.    
    email_remote_host_name : www.qa-rocheconnect.com
    email_remote_url : https://${pas.email_remote_host_name}:94/email-web

    locale_service_remote_url : ${pas.application_remote_url}
    #accessDenied page
    access_denied_url : /accessdenied.html

    transaction.enabled: true
          
    #service registry check - default value server change as client if service registry is enabled
    service.discovery: server

    #To enable and disable rabbitMQ- default value false
    rabbitmq.enabled: false
    #Auditable History enable or disable -defauls value is true
    auditable_history: true
    auditable_history_days: 30
    #AuditTrail enable or disable -default value is false
    audittrail: true
    #routing_key_prefix: Roche.X800.DM.Audit
    #routing_header_name: rabbitmq.ROUTING_KEY

    #pluginuserdomain: SYSTEM
    #plugindomainname: hcl.com
    #Provide the applicable role which applicant can create user with that role 
    #applicableRole:Admin
    #Configure microservice urls here for company and user sync when rabbitmq is diabled.Add mulitple URLs separated by commas
    microservice_url: https://${pas.email_remote_host_name}:94/email-web,https://www.qa-rocheconnect.com:96/omm,https://www.qa-rocheconnect.com:99/wfm,https://www.qa-rocheconnect.com:9090/imm,https://www.qa-rocheconnect.com:86/rmm,https://www.qa-rocheconnect.com:88/amm,https://www.qa-rocheconnect.com:97/adm,https://www.qa-rocheconnect.com:85/device-management,https://www.qa-rocheconnect.com:73/audit-trail-boot

    password_reset_url : https://www.qa-rocheconnect.com:8080/admin_ui/#/reset-password;code=

#######################################################
# if ssl is enabled configure the default port for http if required
#######################################################
    support_for_http_and_https: false
    http_port: 92
    
#######################################################
    #Root company 
    #######################################################
    companyName : root Company
    description	: root company
    domainName : hcl.com
    companyType : PASCOMPANY

    #######################################################
    #Encryption Details- Security token(EmailCreation)
    #######################################################
    encryption_salt : user@domain
    encrypt_password : domain@user
    no_of_iteration : 1

    #######################################################
    #PasswordReset for first time -Details
    #expiry value in days
    #######################################################
    expiryValue : 5

    #######################################################
    #Data for Keystore
    #######################################################
    keystore_location : keystore/pas.jceks
    keystore_pass : pas123
    keystore_type : jceks
    token_private_key_pass : pas123
    token_private_key_alias : pasprivatekey
    token_public_key_alias : paspublickey
    symmetric_key_alias : passymmetrickey
    symmetric_key_pass : pas123
    use_private_for_encryption : true
    
    #######################################################
    #Data for Application excel file Location
    # excels can be loaded from either the classpath or from absolute path.
    #######################################################
    fileName_Prefix : pas_admin_api_init
    XL_Location :  file:///home/rconnect/roche/scripts/connect_yaml/excels
    XL_Prefix : app

    #######################################################
    # Poll the following url for starting the deployment of the application. A get request will be issued to that page and a return value of "YES" or "yes" is required to proceed. 
    # Till then application will loop without starting the initialization. After the expiry of number of attempts, application will throw an exception and exit without initialization. 
    #######################################################
    poll_enabled : true
    poll_attempts : 10
    poll_attempts_delay_in_seconds : 30
    poll_url : ${pas.metadata_remote_url}/poll, ${pas.security_remote_url}/poll

    #######################################################
    # Field names to be excluded from entity class.
    # Default Time Zone
    #######################################################
    all_entities_exclude_list : id,enabled,leftIndex,retired,parentCompany,modifiedDate,editedBy,companyType,rightIndex,createDate
    default_TimeZone : GMT

    #######################################################
    # In case of user name being unique and user not provisioned yet, then create the user under the following company.
    # set allow origin
    # Post to this url after provisioning the user.
    #######################################################
    default_company_for_user_provisioning : hcl.com
    access_control_allow_origin : '*'
    provisioning_success_post_url : ${pas.security_url}/j_saml_authentication
    
    

    #######################################################
    #https-configuring client side truststore and ketysore
    #Enable this for protection of remote web services with protection
    #######################################################
    #client_keystore : C:/Program Files/Java/jdk1.8.0_45/jre/lib/security/keystore.jks
    #client_truststore : C:/Program Files/Java/jdk1.8.0_45/jre/lib/security/keystore.jks
    #cert_provider : SunX509
    #cert_file_type : jks
    #cert_password : changeit

    #######################################################
    #Specific module name for logger
    #######################################################
    logged_module_name : admin-api
    application_module_name : default

    #######################################################
    #rabbitmq properties
    #######################################################
    rabbitmq:
        exchangename : pasExchange
        hierarchyqueuename : adminAPIHierarchyQueue
        userqueuename : adminAPIUserQueue
        userdeletequeuename : adminAPIUserDeleteQueue
        userupdatedqueuename : adminAPIUserUpdatedQueue

    #######################################################
    # CAUTION: PLEASE READ COMMENTS BEFORE ENTERING VALUES. CAN CAUSE CATASTROPHIC FAILURE
    # if the hierarchy sync finds a a company type entity locally it will skip sync
    # if we need to force sync despite type being managed locally, include the entities here.
    #######################################################
    hierarchy_sync_exclude : PASCOMPANY

    #######################################################        
    # Whitelist urls to be validated for application module domain
    #e.g. for multiple domains to be seperated by commas whitelist_urls = www.pas.com,www.test.com,www.sample.com
    #If empty all domains are allowed
    #######################################################
    whitelist_urls : 

## Provide a valid class name if not using jndi. 
## If not provided, spring boot's default connection pool datasource will be used.
    datasource.class : com.mchange.v2.c3p0.ComboPooledDataSource
    
    version: 4.4
    title: '${pas.logged_module_name} REST documentation'
    contact_email: 'PBASolutionsteam@hcl.in'
    api_description: 'These are the contracts for the rest services exposed in this ${pas.logged_module_name}'

    ###############################################
    # Enable the Resource Monitoring for this Microservice 
    # Values - true or false
    # Duration - in seconds
    ###############################################
    monitor_service: false
    monitor_service_duration: 300
    
    
    #######################################################
    # Enable this property to 
    # 1. load the entries of services applicable for service metadata customization
    # 2. Inorder to incorporate changes to metadata component, if there is a change in metadata of the customizable services registered
    # IN DETAIL : When this property is enabled the bootstrap service will try to find the service classes annotated 
    # with @CustomizableService and it's methods annotated with @CustomizableMethod and registers all of 
    # it's complete metadata to metadata component
    #######################################################
    customizableservice.metadata.capture: false
    eventpublishing.queue.default_name: pasQueue
    
#######################################################
#spring boot properties
#######################################################
spring.main.show-banner: false
endpoints.enabled: false
spring.profiles.active: full,permission

spring.cloud.consul.host: www.qa-rocheconnect.com
spring.cloud.consul.port: 8500
spring.application.name: admin-api
spring.cloud.consul.discovery.healthCheckPath: ${management.contextPath}
spring.cloud.consul.discovery.healthCheckInterval: 15s
spring.cloud.consul.discovery.address: ${management.contextPath}
spring.cloud.consul.discovery.instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
    contextPath: /admin-api/poll

#Make it true if service registry is required, default value is false  
spring.cloud.consul.enabled: false

logging.path: '/var/log/connect/log'
logging.file: adminapi.log
logging.config: 'classpath:log4j2.xml'

spring.rabbitmq.host : www.qa-rocheconnect.com
spring.rabbitmq.port : 5672
spring.rabbitmq.username : userone
spring.rabbitmq.password : userone

#######################################################       
# To disable the default configuration for the freemarker
# configuration to search for the templates
# TO BE IGNORED ALWAYS: Since String template loader is used
#######################################################
spring.freemarker.checkTemplateLocation: false

#######################################################
#security.basic.enabled=false
#######################################################       
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
#######################################################
server:
    port: 92
    session-timeout: 600
    context-path: /admin-api
    ssl.enabled : true
    ssl.key-store: /home/rconnect/roche/crts/KeyStore.jks
    ssl.key-store-password: changeit
    ssl.keyStoreProvider : SUN
    ssl.keyStoreType : JKS
    ssl.keyAlias: www.qa-rocheconnect.com

######################################################    
# DATABASE CONFIGURATIONS
#######################################################
spring.datasource.jdbcUrl : jdbc:postgresql://localhost:5432/pas-admin
spring.datasource.user : postgres
spring.datasource.password : postgres123
spring.datasource.driverClass : org.postgresql.Driver
spring.jpa.database-platform : org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.driverClass : com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.database-platform : org.hibernate.dialect.SQLServerDialect
#spring.datasource.jdbcUrl : jdbc:sqlserver://DS-SGH534RR38\\SQLEXPRESS:1433;DatabaseName=pas-admin
#spring.datasource.user : sa
#spring.datasource.password : Password@123

#Keep the consulConfigKeys value blank so that it won;t look into consul
#else provide the structure like as in consul: config/common/data or config/security-web/data 
pas.consulConfigUrl : localhost
#pas.consulConfigKeys : common,security-web
pas.consulConfigKeys : 
pas.consulConfigKeysPrefix : config/
pas.consulConfigKeysSuffix : /data
pas.externalyaml : false

#If you want to encrypt a field enclose with ENC() or OBF
#Generate the string to encrypt using the utility and follow below sample convention
#Also use normal text if applicable
#spring.datasource.password : ENC(RhBRYm0ydOABAvR+hUAk6Q==)
#spring.datasource.password : OBF(Bh/oZZalRbegEkHtWNYNyw==)

#spring.datasource.jdbcUrl : jdbc:derby://localhost:1527/db_data/pas-admin;create=true
#spring.datasource.jdbcUrl : jdbc:derby:D:/PasDB/pas-admin;create=true
#spring.datasource.user : root
#spring.datasource.password : root
spring.datasource.minPoolSize : 5
spring.datasource.maxPoolSize : 50
spring.datasource.acquireIncrement : 1
spring.datasource.maxIdleTime : 600
spring.datasource.idleConnectionTestPeriod : 3000
spring.datasource.testConnectionOnCheckout : true
#spring.datasource.driverClass : org.apache.derby.jdbc.ClientDriver
#spring.datasource.driverClass : org.apache.derby.jdbc.EmbeddedDriver

#spring.jpa.database-platform : org.hibernate.dialect.DerbyTenSevenDialect
spring.jpa.show-sql : false
spring.jpa.hibernate.ddl-auto : update
spring.jpa.generate-ddl : true
spring.jpa.properties.hibernate.cache.use_second_level_cache : false
spring.jpa.properties.hibernate.cache.use_query_cache : true
Spring.jpa.properties.hibernate.query.plan_cache_max_size : 256
spring.jpa.properties.hibernate.cache.use_structured_entries : false
spring.jpa.properties.hibernate.cache.use_minimal_puts : false
spring.jpa.properties.hibernate.cache.generate_statistics : false
spring.jpa.properties.hibernate.cache.provider_configuration : /ehcache.xml
spring.jpa.properties.hibernate.cache.region.factory_class : org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
spring.jpa.properties.javax.persistence.sharedCache.mode : ENABLE_SELECTIVE
#spring.jpa.hibernate.use-new-id-generator-mappings : false
#derby.language.sequence.preallocator : 65535
#spring.jpa.hibernate.use-new-id-generator-mappings : true

#######################################################
# configuration for spring boot read datasource configuration
# FIXME : Use default datasource configuration instead of c3p0
#######################################################
#spring.read.datasource.default.driverClass : com.mysql.jdbc.Driver
#spring.read.datasource.default.jdbcUrl : jdbc:postgresql://localhost:5432/pas-admin?useUnicode=yes&characterEncoding=UTF-8
#spring.read.datasource.default.user : root
#spring.read.datasource.default.password : admin
#spring.read.datasource.default.idleConnectionTestPeriod : 3000
#spring.read.datasource.default.maxPoolSize : 5
#spring.read.datasource.default.minPoolSize : 2
#spring.read.datasource.default.testConnectionOnCheckout : true
#spring.read.datasource.default.debugUnreturnedConnectionStackTraces : true
#######################################################
#default value is false, enable if https is used
https_enabled: true
#######################################################
#ssl configuration
#######################################################
ssl_disabled_protocols: SSL,SSLv2,SSLv2Hello,SSLv3,TLSv1,TLSv1.1
ssl_included_ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
ssl_excluded_ciphers: SSL2_RC4_64_WITH_MD5
#######################################################
#liscense_property_path: C:\Softwares\License\License\gokilaadminapilicense.properties
license_property_path: /home/rconnect/roche/pas/commonlicense.properties
#ancestor_data_acccess_disabled : true
---



spring:

    profiles: docker



pas:

    application_host_name :  adminapi

    application_ui_host_name :  adminui

    security_host_name :  security

    metadata_host_name :  metadata

    application_remote_host_name :  adminapi

    security_remote_host_name :  security

    metadata_remote_host_name :  metadata

    email_remote_host_name : email

    whitelist_urls : 

    access_control_allow_origin : '*'

server:

    port: 80   

 

---

pas.user.rest.service.value: true
pas.i18n.rest.service.value: true
pas.enumeration.rest.service.value: true
pas.company.rest.service.value: true
