use connect-amm;

INSERT INTO assay_type(assaytype_id, active_flag, assay_type, assay_version, workflow_def_file, workflow_file_version,companyid) VALUES(2,'Y','NIPTDPCR','V1','NIPTDPCR_Wfm_v1.bpmn.xml','V1',1);

INSERT INTO sample_type(sampletype_id, active_flag, max_age_days, sample_type, assaytype_id, assay_type,companyid) VALUES (2, 'Y', 7, 'Plasma', 2, 'NIPTDPCR',1);

INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid) VALUES (21, 'Y', 'MP96', 'Harmony Prenatal Test (T21, T18, T13)', 'Cellular RNA LV', 2, 'NIPTDPCR', 'NA Extraction',1,1);
INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid) VALUES (22, 'Y', 'MP96', 'Fetal Sex', 'Cellular RNA LV', 2, 'NIPTDPCR', 'NA Extraction',2,1);
INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid) VALUES (23, 'Y', 'LP24', 'Harmony Prenatal Test (T21, T18, T13)', 'LPdPCR', 2, 'NIPTDPCR','Library Preparation',1,1);
INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid) VALUES (24, 'Y', 'LP24', 'Fetal Sex', 'LPdPCR', 2, 'NIPTDPCR','Library Preparation',2,1);
INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid,analysis_package_name) VALUES (25, 'Y', 'dPCR Analyzer', 'Harmony Prenatal', 'dPCRAnalyzerAssay1', 2, 'NIPTDPCR','dPCR',1,1,'AP1');
INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid,analysis_package_name) VALUES (26, 'Y', 'dPCR Analyzer', 'Fetal Sex', 'dPCRAnalyzerAssay1', 2, 'NIPTDPCR','dPCR',2,1,'AP1');
--INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid,test_protocol_version) VALUES (27, 'Y', 'dPCR Analyzer', 'Harmony Prenatal', 'dPCRAnalyzerAssay2', 2, 'NIPTDPCR','dPCR',1,1,'1.1');
--INSERT INTO device_test_options(device_test_option_id, active_flag, device_type, test_name, test_protocol, assaytype_id, assay_type, process_step_name, test_option_id,companyid,test_protocol_version) VALUES (28, 'Y', 'dPCR Analyzer', 'Fetal Sex', 'dPCRAnalyzerAssay2', 2, 'NIPTDPCR','dPCR',2,1,'1.1');




INSERT INTO test_options(test_option_id, active_flag, sequence_id, test_name,test_description, assaytype_id, assay_type,companyid) VALUES (5, 'Y', 5, 'Harmony Prenatal Test (T21, T18, T13)', 'Harmony Prenatal Test (T21, T18, T13)', 2, 'NIPTDPCR',1);
INSERT INTO test_options(test_option_id, active_flag, sequence_id, test_name,test_description, assaytype_id, assay_type,companyid) VALUES (6, 'Y', 6, 'Fetal Sex', 'Fetal Sex', 2, 'NIPTDPCR',1);
--INSERT INTO test_options(test_option_id, active_flag, sequence_id, test_name,test_description, assaytype_id, assay_type,companyid) VALUES (7, 'Y', 7, 'FetalSex', 'Fetal Sex', 2, 'NIPTDPCR',1);
--INSERT INTO test_options(test_option_id, active_flag, sequence_id, test_name,test_description, assaytype_id, assay_type,companyid) VALUES (8, 'Y', 8, 'MX', 'MX', 2, 'NIPTDPCR',1);

INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name,assaytype_id, assay_type,input_container_type, output_container_type,sample_volume,eluate_volume,reagent,companyid) VALUES (7, 'Y','MP96', 'Y',1,'NA Extraction', 2, 'NIPTDPCR','96 Well plate','96 Well plate','200','50','Cellular RNA LV',1);
INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,sample_volume,eluate_volume,reagent,companyid) VALUES (8, 'Y', 'LP24', 'Y',2,'Library Preparation', 2, 'NIPTDPCR','96 Well plate','dPCR Chip','50','40','LP24_dPCR Protocol',1);
--INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,sample_volume,eluate_volume,reagent,companyid) VALUES (9, 'Y', '', 'Y',3,'dPCR', 2, 'NIPTDPCR','','','','','',1);
INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,sample_volume,eluate_volume,reagent,companyid) VALUES (9, 'Y', 'dPCR Analyzer', 'Y',3,'dPCR', 2, 'NIPTDPCR',null,null,null,null,null,1);
INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,sample_volume,eluate_volume,reagent,companyid) VALUES (10, 'Y', null, 'Y',4,'Analysis', 2, 'NIPTDPCR','','','','','',1);
--INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,companyid) VALUES (9, 'Y', 'LP24', 'Y',9,'LP Post PCR/Pooling',2, 'NIPTDPCR','PCR plate','PCR plate',1);
--INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,companyid) VALUES (10, 'Y', 'LP24', 'Y',10,'LP Sequencing Prep',2, 'NIPTDPCR','PCR plate','Pool tube',1);
--INSERT INTO process_step_action(proc_step_action_id, active_flag, device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,companyid) VALUES (11, 'Y', 'HTP', 'Y',11,'Sequencing',2, 'NIPTDPCR','Pool tube','Consumable device',1);
--INSERT INTO process_step_action(proc_step_action_id, active_flag,device_type, manual_verification_flag,process_step_seq,process_step_name, assaytype_id, assay_type,input_container_type, output_container_type,companyid) VALUES (12, 'Y', 'FORTE', 'Y',12,'Analysis',2, 'NIPTDPCR','Sequencing run directory','Analysis output directory',1);

INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, max_val, min_val, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (4, 'Y', 'NA', 'Maternal Age', 100, 0, 2, 'NIPTDPCR',1,'data validation','NA');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, max_val, min_val, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (5, 'Y', 'NA', 'Gestational Age Weeks', 40, 10,2, 'NIPTDPCR',1,'data validation','NA');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, max_val, min_val, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (6, 'Y', 'NA', 'Gestational Age Days', 6, 0,2, 'NIPTDPCR',1,'data validation','NA');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, max_val, min_val, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (8, 'Y', 'NA', 'Egg Donor Age', 76, 12,2, 'NIPTDPCR',1,'data validation','NA');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (26, 'Y', 'NA', 'Comments', 2, 'NIPTDPCR',1,'mandatory flag','false');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (27, 'Y', 'NA', 'Maternal age', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (28, 'Y', 'NA', 'Gestational age', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (29, 'Y', 'NA', 'IVF status', 2, 'NIPTDPCR',1,'mandatory flag','true');
--INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (30, 'Y', 'NA', 'Egg Donor', 2, 'NIPTDPCR',1,'mandatory flag','false');
--INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (31, 'Y', 'NA', 'Egg donor age', 2, 'NIPTDPCR',1,'mandatory flag','false');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (32, 'Y', 'NA', 'Number of fetus', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (33, 'Y', 'NA', 'First name', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (34, 'Y', 'NA', 'Last name', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (35, 'Y', 'NA', 'Medical record number', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (36, 'Y', 'NA', 'DOB', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (37, 'Y', 'NA', 'Referring clinician', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (38, 'Y', 'NA', 'Laboratory ID', 2, 'NIPTDPCR',1,'mandatory flag','true');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (39, 'Y', 'NA', 'Other clinician', 2, 'NIPTDPCR',1,'mandatory flag','false');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (40, 'Y', 'NA', 'Clinic name', 2, 'NIPTDPCR',1,'mandatory flag','false');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (41, 'Y', 'NA', 'Reason for Referral', 2, 'NIPTDPCR',1,'mandatory flag','false');
INSERT INTO assay_data_validations(assay_validation_id, active_flag, expression, field_name, assaytype_id, assay_type,companyid,group_name,is_mandatory) VALUES (42, 'Y', 'NA', 'Account #', 2, 'NIPTDPCR',1,'mandatory flag','false');


INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (9, 'Y', 'ivf status', 'Yes', 2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (10, 'Y', 'ivf status', 'No', 2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (11, 'Y', 'ivf status', 'Missing', 2, 'NIPTDPCR',1);
--INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (15, 'Y', 'egg donor', 'No',2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (12, 'Y', 'egg donor', 'Self',2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (13, 'Y', 'egg donor', 'Non-self',2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (14, 'Y', 'egg donor', 'Missing',2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (15, 'Y', 'Number of Fetus', '1',2, 'NIPTDPCR',1);
INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (16, 'Y', 'Number of Fetus', '2',2, 'NIPTDPCR',1);
--INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (21, 'Y', 'Number of Fetus', '>2',2, 'NIPTDPCR',1);
--INSERT INTO assay_listdata(assay_listdata_id, active_flag, list_type, "value", assaytype_id, assay_type,companyid) VALUES (22, 'Y', 'Number of Fetus', 'Missing',2, 'NIPTDPCR',1);