INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (1,'Y','NIPTDPCR', 'MP96', 'F1',  'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (2,'Y', 'NIPTDPCR', 'MP96', 'F2', 'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (3,'Y', 'NIPTDPCR', 'MP96', 'F3',  'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (4,'Y', 'NIPTDPCR', 'MP96', 'F4',  'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (5,'Y', 'NIPTDPCR', 'MP96', 'F5','Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (6,'Y', 'NIPTDPCR', 'MP96', 'F6', 'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (7,'Y', 'NIPTDPCR', 'MP96', 'F7',  'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (8,'Y', 'NIPTDPCR', 'MP96', 'F8',  'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (9,'Y', 'NIPTDPCR', 'MP96', 'F9',  'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (10,'Y', 'NIPTDPCR', 'MP96', 'F10',  'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (11,'Y', 'NIPTDPCR', 'MP96', 'F11', 'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (12,'Y', 'NIPTDPCR', 'MP96', 'F12',  'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (13,'Y', 'NIPTDPCR', 'MP96', 'F13', 'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (14,'Y', 'NIPTDPCR', 'MP96', 'F14',  'Warning','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (15,'Y', 'NIPTDPCR', 'MP96', 'F15',  'Fatal','NA Extraction', 'All samples in a run',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (16,'Y', 'NIPTDPCR', 'MP96', 'F16',  'Fatal','NA Extraction', 'Samples',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (17,'Y', 'NIPTDPCR', 'MP96', 'F17',  'Fatal','NA Extraction', 'Samples',2, 1);

INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (18,'Y', 'NIPTDPCR', 'LP24', 'F1', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (19,'Y', 'NIPTDPCR', 'LP24', 'F2', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (20,'Y', 'NIPTDPCR', 'LP24', 'F3', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (21,'Y', 'NIPTDPCR', 'LP24', 'F4',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (22,'Y', 'NIPTDPCR', 'LP24', 'F5',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (23,'Y', 'NIPTDPCR', 'LP24', 'F6',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (24,'Y', 'NIPTDPCR', 'LP24', 'F7', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (25,'Y', 'NIPTDPCR', 'LP24', 'F8', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (26,'Y', 'NIPTDPCR', 'LP24', 'F9',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (27,'Y', 'NIPTDPCR', 'LP24', 'F10', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (28,'Y', 'NIPTDPCR', 'LP24', 'F12', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (29,'Y', 'NIPTDPCR', 'LP24', 'F13',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (30,'Y', 'NIPTDPCR', 'LP24', 'F14', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (31,'Y', 'NIPTDPCR', 'LP24', 'F15',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (32,'Y', 'NIPTDPCR', 'LP24', 'F17', 'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (33,'Y', 'NIPTDPCR', 'LP24', 'F18',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (34,'Y', 'NIPTDPCR', 'LP24', 'F19',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (35,'Y', 'NIPTDPCR', 'LP24', 'F20', 'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (36,'Y', 'NIPTDPCR', 'LP24', 'F21',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (37,'Y', 'NIPTDPCR', 'LP24', 'F22', 'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (38,'Y', 'NIPTDPCR', 'LP24', 'F23', 'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (39,'Y', 'NIPTDPCR', 'LP24', 'F24',  'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (40,'Y', 'NIPTDPCR', 'LP24', 'F25',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (41,'Y', 'NIPTDPCR', 'LP24', 'F26',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (42,'Y', 'NIPTDPCR', 'LP24', 'F27',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (43,'Y', 'NIPTDPCR', 'LP24', 'F28',  'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (44,'Y', 'NIPTDPCR', 'LP24', 'F29','Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (45,'Y', 'NIPTDPCR', 'LP24', 'F30',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (46,'Y', 'NIPTDPCR', 'LP24', 'F32',  'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (47,'Y', 'NIPTDPCR', 'LP24', 'F33', 'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (48,'Y', 'NIPTDPCR', 'LP24', 'F34', 'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (49,'Y', 'NIPTDPCR', 'LP24', 'F35',  'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (50,'Y', 'NIPTDPCR', 'LP24', 'F36',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (51,'Y', 'NIPTDPCR', 'LP24', 'F37',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (52,'Y', 'NIPTDPCR', 'LP24', 'F38', 'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (53,'Y', 'NIPTDPCR', 'LP24', 'F39', 'Critical','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (54,'Y', 'NIPTDPCR', 'LP24', 'F40',  'Information','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (55,'Y', 'NIPTDPCR', 'LP24', 'F41',  'Fatal','Library Preparation', 'Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (56,'Y', 'NIPTDPCR', 'LP24', 'F42',  'Critical','Library Preparation', 'Sample',2, 1);

INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (57,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT001',  'Fatal','dPCR', 'Sample', 2,1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (58,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT002',  'Fatal', 'dPCR','Sample', 2,1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (59,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT003',  'Critical','dPCR', 'Sample', 2,1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (60,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT004', 'Warning', 'dPCR','Sample', 2,1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (61,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT005', 'Fatal', 'dPCR','Sample', 2,1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (62,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT006', 'Fatal', 'dPCR','Sample',2, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (63,'Y', 'NIPTDPCR', 'dPCR Analyzer', 'AT007', 'Fatal','dPCR', 'Sample',2, 1);

INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (64,'Y', 'NIPTHTP', 'MP24', 'F1', 'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (65,'Y', 'NIPTHTP', 'MP24', 'F2', 'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (66,'Y', 'NIPTHTP', 'MP24', 'F3', 'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (67,'Y', 'NIPTHTP', 'MP24', 'F4',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (68,'Y', 'NIPTHTP', 'MP24', 'F5',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (69,'Y', 'NIPTHTP', 'MP24', 'F6',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (70,'Y', 'NIPTHTP', 'MP24', 'F7',  'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (71,'Y', 'NIPTHTP', 'MP24', 'F8',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (72,'Y', 'NIPTHTP', 'MP24', 'F9',  'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (73,'Y', 'NIPTHTP', 'MP24', 'F10',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (74,'Y', 'NIPTHTP', 'MP24', 'F12',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (75,'Y', 'NIPTHTP', 'MP24', 'F13',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (76,'Y', 'NIPTHTP', 'MP24', 'F14',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (77,'Y', 'NIPTHTP', 'MP24', 'F15', 'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (78,'Y', 'NIPTHTP', 'MP24', 'F17', 'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (79,'Y', 'NIPTHTP', 'MP24', 'F18',  'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (80,'Y', 'NIPTHTP', 'MP24', 'F19',  'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (81,'Y', 'NIPTHTP', 'MP24', 'F20', 'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (82,'Y', 'NIPTHTP', 'MP24', 'F21',  'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (83,'Y', 'NIPTHTP', 'MP24', 'F22',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (84,'Y', 'NIPTHTP', 'MP24', 'F23', 'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (85,'Y', 'NIPTHTP', 'MP24', 'F24',  'Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (86,'Y', 'NIPTHTP', 'MP24', 'F25',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (87,'Y', 'NIPTHTP', 'MP24', 'F26',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (88,'Y', 'NIPTHTP', 'MP24', 'F27',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (89,'Y', 'NIPTHTP', 'MP24', 'F28', 'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (90,'Y', 'NIPTHTP', 'MP24', 'F29',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (91,'Y', 'NIPTHTP', 'MP24', 'F30', 'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (92,'Y', 'NIPTHTP', 'MP24', 'F32',  'Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (93,'Y', 'NIPTHTP', 'MP24', 'F33',  'Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (94,'Y', 'NIPTHTP', 'MP24', 'F34','Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (95,'Y', 'NIPTHTP', 'MP24', 'F35', 'Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (96,'Y', 'NIPTHTP', 'MP24', 'F36',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (97,'Y', 'NIPTHTP', 'MP24', 'F37',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (98,'Y', 'NIPTHTP', 'MP24', 'F38', 'Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (99,'Y', 'NIPTHTP', 'MP24', 'F39', 'Critical','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (100 ,'Y','NIPTHTP', 'MP24', 'F40', 'Information','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (101,'Y', 'NIPTHTP', 'MP24', 'F41',  'Fatal','NA Extraction', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (102,'Y', 'NIPTHTP', 'MP24', 'F42',  'Critical','NA Extraction', 'Sample',1, 1);

INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (103,'Y', 'NIPTHTP', 'LP24', 'F1', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (104,'Y', 'NIPTHTP', 'LP24', 'F2',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (105,'Y', 'NIPTHTP', 'LP24', 'F3', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (106,'Y', 'NIPTHTP', 'LP24', 'F4',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (107,'Y', 'NIPTHTP', 'LP24', 'F5', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (108,'Y', 'NIPTHTP', 'LP24', 'F6',  'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (109,'Y', 'NIPTHTP', 'LP24', 'F7', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (110,'Y', 'NIPTHTP', 'LP24', 'F8',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (111,'Y', 'NIPTHTP', 'LP24', 'F9',  'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (112,'Y', 'NIPTHTP', 'LP24', 'F10', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (113,'Y', 'NIPTHTP', 'LP24', 'F12',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (114,'Y', 'NIPTHTP', 'LP24', 'F13', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (115,'Y', 'NIPTHTP', 'LP24', 'F14',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (116,'Y', 'NIPTHTP', 'LP24', 'F15', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (117,'Y', 'NIPTHTP', 'LP24', 'F17', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (118,'Y', 'NIPTHTP', 'LP24', 'F18', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (119,'Y', 'NIPTHTP', 'LP24', 'F19', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (120,'Y', 'NIPTHTP', 'LP24', 'F20', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (121,'Y', 'NIPTHTP', 'LP24', 'F21',  'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (122,'Y', 'NIPTHTP', 'LP24', 'F22', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (123,'Y', 'NIPTHTP', 'LP24', 'F23', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (124,'Y', 'NIPTHTP', 'LP24', 'F24', 'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (125,'Y', 'NIPTHTP', 'LP24', 'F25', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (126,'Y', 'NIPTHTP', 'LP24', 'F26', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (127,'Y', 'NIPTHTP', 'LP24', 'F27',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (128,'Y', 'NIPTHTP', 'LP24', 'F28', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (129,'Y', 'NIPTHTP', 'LP24', 'F29','Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (130,'Y', 'NIPTHTP', 'LP24', 'F30',  'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (131,'Y', 'NIPTHTP', 'LP24', 'F32', 'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (132,'Y', 'NIPTHTP', 'LP24', 'F33',  'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (133,'Y', 'NIPTHTP', 'LP24', 'F34',  'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (134,'Y', 'NIPTHTP', 'LP24', 'F35', 'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (135,'Y', 'NIPTHTP', 'LP24', 'F36', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (136,'Y', 'NIPTHTP', 'LP24', 'F37', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (137,'Y', 'NIPTHTP', 'LP24', 'F38', 'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (138,'Y', 'NIPTHTP', 'LP24', 'F39', 'Critical','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (139,'Y', 'NIPTHTP', 'LP24', 'F40', 'Information','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (140,'Y', 'NIPTHTP', 'LP24', 'F41', 'Fatal','Library Preparation', 'Sample',1, 1);
INSERT INTO flags_data(flag_id,active_flag, assay_type,device_type,flag_code, flag_severity, process_step_name, sample_or_runlevel, assaytype_id, companyid)
VALUES (141,'Y', 'NIPTHTP', 'LP24', 'F42', 'Critical','Library Preparation', 'Sample',1, 1);