DROP DATABASE IF EXISTS "adapter-dpcr";
DROP DATABASE IF EXISTS "connect-adm";
DROP DATABASE IF EXISTS "connect-amm";
DROP DATABASE IF EXISTS "connect-imm";
DROP DATABASE IF EXISTS "connect-omm";
DROP DATABASE IF EXISTS "connect-rmm";
DROP DATABASE IF EXISTS "connect-wfm";
DROP DATABASE IF EXISTS "htp-forte-adapter";
DROP DATABASE IF EXISTS "mp96-adapter";
DROP DATABASE IF EXISTS "mp24-adapter";
DROP DATABASE IF EXISTS "lp24-adapter";
DROP DATABASE IF EXISTS "AuditTrailDB";
DROP DATABASE IF EXISTS "pas-device";
DROP DATABASE IF EXISTS "pas-admin";
DROP DATABASE IF EXISTS "pas-email";
DROP DATABASE IF EXISTS "pas-metadata";
DROP DATABASE IF EXISTS "pas-security";

CREATE DATABASE "adapter-dpcr";
CREATE DATABASE "connect-adm";
CREATE DATABASE "connect-amm";
CREATE DATABASE "connect-imm";
CREATE DATABASE "connect-omm";
CREATE DATABASE "connect-rmm";
CREATE DATABASE "connect-wfm";
CREATE DATABASE "htp-forte-adapter";
CREATE DATABASE "mp96-adapter";
CREATE DATABASE "mp24-adapter";
CREATE DATABASE "lp24-adapter";
CREATE DATABASE "AuditTrailDB";
CREATE DATABASE "pas-device";
CREATE DATABASE "pas-admin";
CREATE DATABASE "pas-email";
CREATE DATABASE "pas-metadata";
CREATE DATABASE "pas-security";